### ISSUE TITLE
consider revising some default settings and adding to README

### ISSUE THREAD

**Issue by JackDougherty** [HandsOnDataViz/chartjs-line#1]
1) Consider changing line chart default colors, based on https://colorbrewer2.org/#type=qualitative&scheme=Dark2&n=3
```
        plugins: {
          colorschemes: {
            scheme: 'brewer.DarkTwo3'
```
Also mention the color brewer plugin in the README, since users may not see it down at bottom of code

2) I think you meant to write "Y-axis" here?
```
var BEGIN_AT_ZERO = false;  // Should x-axis start from 0? `true` or `false`
```

3) In the default line chart, the point styles are all the same default (circles), which means we cannot distinguish between them except by color. If there's no easy way to designate different styles (since we don't know the number of data series), perhaps change 'circle' to none, if possible?
https://www.chartjs.org/docs/latest/configuration/elements.html#point-styles

4) Consider mentioning some common items in README that users may wish to add to customize code, such as reducing the number of tick marks in the horizontal axis of a line chart:
```
            ticks: {
              maxTicksLimit: 11,
```
and adding $ symbol to an axis:
```
ticks: {
              beginAtZero: BEGIN_AT_ZERO,
              callback: function(value, index, values) {
                return '$' + value.toLocaleString()
              }
```
5) Note in README that users must modify caption/source info in the index.html

**Comment by ilyankou** [comment]
Jack:

1. I updated the scheme, but to a 5-color version (not 3-color) because we have 5 lines in the example data.
1. Fixed.
1. We cannot remove points because tooltips appear when you hover over them. I left them as circles.
1. Expanded README to include the modifications you suggested.
1. Done.

**Comment by JackDougherty** [comment]
All of this looks great -- thanks!
