### ISSUE TITLE
Doesn't detect CSV changes

### ISSUE THREAD

**Issue by Justinzobel** [HandsOnDataViz/chartjs-line#3]
When I change the data in the CSV and refresh or force refresh it doesn't change on the chart.

**Comment by JackDougherty** [comment]
@Justinzobel - Thanks for reporting this issue. I'm cc:ing our developer to look into it

@ilyankou - I can confirm that this code template is not behaving as expected:
- I download the template to my local computer
- I updated and saved the CSV data
- I do a hard-refresh in Safari (with CORS disabled)
- the line chart does *not* auto-update to display the new data. 

Instead, I need to open the index.html in a new tab to see changes. 

Any ideas about how to revise the code to address this? Also may need to check other chart.js templates.

**Comment by JackDougherty** [comment]
@ilyankou - I noticed this change in the Chart.js v3 migration guide:

Chart.js is no longer providing the Chart.bundle.js and Chart.bundle.min.js. Please see the installation and integration docs for details on the recommended way to setup Chart.js if you were using these builds.

https://www.chartjs.org/docs/latest/getting-started/v3-migration.html#_3-x-migration-guide

See also new info about Updating Charts
It's pretty common to want to update charts after they've been created. When the chart data or options are changed, Chart.js will animate to the new data values and options.
https://www.chartjs.org/docs/latest/developers/updates.html

**Comment by Justinzobel** [comment]
So does this mean we can't have the data loading from CSV dynamically?

**Comment by ilyankou** [comment]
Thanks both for bringing up the issue & investigating.

>Chart.js is no longer providing the Chart.bundle.js and Chart.bundle.min.js.

We still use v2.8 in all templates, so this shouldn't apply to us.

The issue is with the browsers caching the CSV file, not Chart.js. In Safari, after you change the data, go to `Develop > Empty Caches` before you do the refresh. It should work.

The good news is that:
* Chrome, when running with --disable-web-security flag, updates the data on refresh.
* Our second suggestion of using `live-server` in README works as intended.

@JackDougherty do you think it is worth for me to add cache info to README?

**Comment by Justinzobel** [comment]
How does `live-server` help for a production environment on a hosted server?

Are there instructions on what to change so the CSV data isn't cached?

**Comment by ilyankou** [comment]
@Justinzobel you are right, `live-server` and other techniques listed in README are for local development only. The idea behind the template is once you create the chart, you copy the files to the server and don't change the data too often (so it doesn't matter if users have it cached).

If you have high frequency updates to the CSV file, depending on your production environment, you could add a `Cache-Control` HTTP header to the file to let the browsers know they shouldn't cache the file for too long. See here [for AWS S3](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/Expiration.html#ExpirationAddingHeadersInS3).

Another way to circumvent caching would be to rename `data.csv` to something like `data1.csv`, and change the URL in `script.js` to fetch that file instead. Browsers will think it is a new file, and load it. Unfortunately, it is only possible manually as we didn't use any JavaScript bundling tools for this template (which generate new file names every time you build it).

If you don't use the server where you can add custom HTTP headers such as S3, but need to update the data file very frequently, you may consider using something else.

Hope this is helpful.

**Comment by Justinzobel** [comment]
Yeah I was renaming it each time, that worked but wasn't really a good solution. I have direct access to my host so I can try the Cache-Control, will look into it, thanks.

**Comment by ilyankou** [comment]
@Justinzobel I updated the template code to read the CSV file with `?randomstring` appended to the file path, as described in this [amazing Stackoverflow answer](https://stackoverflow.com/questions/8841425/how-to-set-cache-false-in-jquery-get-call/8841543#8841543). See `script.js` for a quick fix. This should solve your issue.

**Comment by Justinzobel** [comment]
> @Justinzobel I updated the template code to read the CSV file with `?randomstring` appended to the file path, as described in this [amazing Stackoverflow answer](https://stackoverflow.com/questions/8841425/how-to-set-cache-false-in-jquery-get-call/8841543#8841543). See `script.js` for a quick fix. This should solve your issue.

Wow thanks I'll give it a shot now!

**Comment by Justinzobel** [comment]
It works perfectly! Thanks. The js and HTML are still being cached but once I've got them set that won't be an issue. You should definitely set up a way for others to donate to you. I'd like to show my appreciation with a small tip.

**Comment by ilyankou** [comment]
Happy to help, @Justinzobel.

> You should definitely set up a way for others to donate to you. I'd like to show my appreciation with a small tip.

We have GitHub Sponsors set up for the [Hands-On Data Visualization book](https://github.com/HandsOnDataViz/book) repository, which you can use to support us for as long (or short) as you want.

**Comment by Justinzobel** [comment]
I did a donation via GitHub sponsors. It would be nice to have a direct PayPal or LibrePay option for those that want to do a one off easily.
