### ISSUE TITLE
take the data from a mysql table

### ISSUE THREAD

**Issue by Pepepy** [HandsOnDataViz/chartjs-line#4]
How could I take the data from a mysql table instead of a csv?

**Comment by ilyankou** [comment]
Hi @Pepepy 

This example is designed to work fully in front-end, and accessing an SQL database from JavaScript is not something that's done in a browser. One would normally write a REST API to "connect" an interface to a database.

The most straightforward way would be to export your table data as a CSV in pgAdmin or whatever interface you use to interact with your SQL, and then edit in Excel/Google Sheets to make it look similar to the example file.

Ilya
